version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - codegen
  - graphcache
  - movedamageclass
  - movedamageclassnames
  - moveflavortexts
  - movelearnmethod
  - movenames
  - pokemonmoves
  - pokemons
  - pokemonspeciesname
  - pokemonspeciesnames
  - pokemonspecy
  - pokemontypes
  - typenames
  - urql
  - valibot
  - yamatatsu
ignoreWords: []
import: []
