/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SpeciesImport } from './routes/species'
import { Route as IndexImport } from './routes/index'
import { Route as SpeciesSpecieIdImport } from './routes/species.$specieId'

// Create/Update Routes

const SpeciesRoute = SpeciesImport.update({
  id: '/species',
  path: '/species',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SpeciesSpecieIdRoute = SpeciesSpecieIdImport.update({
  id: '/$specieId',
  path: '/$specieId',
  getParentRoute: () => SpeciesRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/species': {
      id: '/species'
      path: '/species'
      fullPath: '/species'
      preLoaderRoute: typeof SpeciesImport
      parentRoute: typeof rootRoute
    }
    '/species/$specieId': {
      id: '/species/$specieId'
      path: '/$specieId'
      fullPath: '/species/$specieId'
      preLoaderRoute: typeof SpeciesSpecieIdImport
      parentRoute: typeof SpeciesImport
    }
  }
}

// Create and export the route tree

interface SpeciesRouteChildren {
  SpeciesSpecieIdRoute: typeof SpeciesSpecieIdRoute
}

const SpeciesRouteChildren: SpeciesRouteChildren = {
  SpeciesSpecieIdRoute: SpeciesSpecieIdRoute,
}

const SpeciesRouteWithChildren =
  SpeciesRoute._addFileChildren(SpeciesRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/species': typeof SpeciesRouteWithChildren
  '/species/$specieId': typeof SpeciesSpecieIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/species': typeof SpeciesRouteWithChildren
  '/species/$specieId': typeof SpeciesSpecieIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/species': typeof SpeciesRouteWithChildren
  '/species/$specieId': typeof SpeciesSpecieIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/species' | '/species/$specieId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/species' | '/species/$specieId'
  id: '__root__' | '/' | '/species' | '/species/$specieId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SpeciesRoute: typeof SpeciesRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SpeciesRoute: SpeciesRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/species"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/species": {
      "filePath": "species.tsx",
      "children": [
        "/species/$specieId"
      ]
    },
    "/species/$specieId": {
      "filePath": "species.$specieId.tsx",
      "parent": "/species"
    }
  }
}
ROUTE_MANIFEST_END */
